// src/app/app.module.ts

import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { HttpClientModule } from '@angular/common/http'; // Required for Apollo Client (HttpLink)
import { ReactiveFormsModule, FormsModule } from '@angular/forms'; // Import BOTH: Reactive for Login/Signup/Add/Edit, FormsModule for ngModel (e.g., in search)
import { CommonModule } from '@angular/common'; // Required for *ngIf, *ngFor, async pipe etc.

// Routing Module
import { AppRoutingModule } from './app-routing.module';

// GraphQL Module (Generated by ng add apollo-angular)
import { GraphQLModule } from './graphql.module';

// Root Component
import { AppComponent } from './app.component';

// Page & Feature Components (Ensure paths are correct)
import { LoginComponent } from './components/login/login.component';
import { SignupComponent } from './components/signup/signup.component';
import { EmployeeListComponent } from './components/employee-list/employee-list.component';
import { EmployeeAddComponent } from './components/employee-add/employee-add.component';
import { EmployeeEditComponent } from './components/employee-edit/employee-edit.component';
import { EmployeeDetailsComponent } from './components/employee-details/employee-details.component'; // If you created this
import { NavbarComponent } from './components/navbar/navbar.component'; // If you created this

// --- Optional: Angular Material Imports (if you used 'ng add @angular/material') ---
// import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
// import { MatInputModule } from '@angular/material/input';
// import { MatButtonModule } from '@angular/material/button';
// import { MatCardModule } from '@angular/material/card';
// import { MatTableModule } from '@angular/material/table';
// import { MatToolbarModule } from '@angular/material/toolbar';
// import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
// import { MatSnackBarModule } from '@angular/material/snack-bar';
// import { MatIconModule } from '@angular/material/icon';
// import { MatDialogModule } from '@angular/material/dialog';
// ... other Material modules you might need

@NgModule({
  declarations: [
    // List all components used within this module
    AppComponent,
    LoginComponent,
    SignupComponent,
    EmployeeListComponent,
    EmployeeAddComponent,
    EmployeeEditComponent,
    EmployeeDetailsComponent, // Include if it exists and is not standalone
    NavbarComponent           // Include if it exists and is not standalone
  ],
  imports: [
    // Angular Core & Common Modules
    BrowserModule,
    HttpClientModule,    // Needed for backend communication (Apollo uses it)
    ReactiveFormsModule, // For reactive forms (Login, Signup, Add, Edit)
    FormsModule,         // For template-driven forms (like [(ngModel)] in search)
    CommonModule,        // For common directives like *ngIf, *ngFor, async pipe

    // Application Routing
    AppRoutingModule,

    // GraphQL Setup
    GraphQLModule,

    // --- Optional: Angular Material Modules ---
    // BrowserAnimationsModule, // Required for most Material animations
    // MatInputModule,
    // MatButtonModule,
    // MatCardModule,
    // MatTableModule,
    // MatToolbarModule,
    // MatProgressSpinnerModule,
    // MatSnackBarModule,
    // MatIconModule,
    // MatDialogModule,
    // ... other Material modules
  ],
  providers: [
    // Services are typically provided in root ('providedIn: 'root'')
    // Guards are also often provided in root
    // If not, list Services or Guards here:
    // AuthService,
    // EmployeeService,
    // AuthGuard
  ],
  bootstrap: [AppComponent] // The main component to bootstrap the application
})
export class AppModule { }